services:
  migrator:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitoriamelo1/rodas:latest
    command: /bin/bash -c "uv run manage.py migrate rodas --noinput"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitoriamelo1/rodas:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    networks:
      - default

  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-rodas}
      POSTGRES_PASSWORD: ${DB_PASS:-rodas}
      POSTGRES_DB: ${DB_NAME:-rodas}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-rodas}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5439:5432"
    networks:
      - default

  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
